version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: i want in
      MYSQL_DATABASE: greenloop
    ports:
      - "3307:3306"

